### ISSUE TITLE
  task 1 failed - "The active subnetwork file does not exist! Check the `active_snw_path` argument"

### ISSUE THREAD

**Issue by ajawd** [egeulgen/pathfindR#24] opened 2019-11-11 00:21 UTC
hello,
i am facing problems with this package even if i use your saved data example am using R studio Version 1.2.5001 and pathfindR version ‘1.4.0’
the error say
  task 1 failed - "The active sub network file does not exist! Check the `active_snw_path` argument"

**Comment by egeulgen** [comment] 2019-11-11 00:56
can you share the commands you ran to reproduce the issue? Is this "RA_input" or "myeloma_input"?

For future reference, please use the [bug report template](https://github.com/egeulgen/pathfindR/issues/new?assignees=&labels=&template=bug_report.md&title=) so that this works faster

**Comment by ajawd** [comment] 2019-11-11 01:27
i used RA input
library(pathfindR)
knitr::kable(head(RA_input))
RA_output <- run_pathfindR(RA_input)
#this is the command i run 
`n_processes` is set to `iterations` because `iterations` < `n_processes`
There is already a directory named "pathfindR_Results".
Writing the result to "pathfindR_Results(5)" not to overwrite any previous results.
## Testing input
The input looks OK
## Processing input. Converting gene symbols,
          if necessary (and if human gene symbols provided)
Number of genes provided in input: 572
Number of genes in input after p-value filtering: 572

Could not find any interactions for 11 (1.92%) genes in the PIN
Final number of genes in input: 561
## Performing Active Subnetwork Search and Enrichment
Error in { : 
  task 1 failed - "The active subnetwork file does not exist! Check the `active_snw_path` argument"
i have also installed java in my computer

**Comment by ajawd** [comment] 2019-11-11 01:29
windows version 10
java version 8 (build 1.8.0_231-b11)
 R studio Version 1.2.5001 
pathfindR version ‘1.4.0’

**Comment by egeulgen** [comment] 2019-11-11 01:49
`RA_input` was tested with `run_pathfindR` on multiple platforms so this is very odd. Can you try a manual run? see [here](https://github.com/egeulgen/pathfindR/wiki/Frequently-encountered-issues#error-in---task-1-failed---cannot-open-the-connection)

**Comment by ajawd** [comment] 2019-11-11 02:41
i have run the manual code as you told me there is also error massage in this command
active_snws <- active_snw_search(processed_data, pin_path, snws_file = "subnetworks", search_method = "GR")
#Error in pathfindR::filterActiveSnws(active_snw_path = snws_file, sig_genes_vec = input_for_search$GENE,  : 
  The active subnetwork file does not exist! Check the `active_snw_path` argument

**Comment by ajawd** [comment] 2019-11-11 04:59
dear sir,
i have run the manual code as you told me there is also error massage in this command
active_snws <- active_snw_search(processed_data, pin_path, snws_file = "subnetworks", search_method = "GR")
#Error in pathfindR::filterActiveSnws(active_snw_path = snws_file, sig_genes_vec = input_for_search$GENE, :
The active subnetwork file does not exist! Check the active_snw_path argument
    On Monday, November 11, 2019, 9:49:43 AM GMT+8, Ege Ulgen <notifications@github.com> wrote:  
 
 
RA_input was tested with run_pathfindR on multiple platforms so this is very odd. Can you try a manual run? see here

**Comment by ajawd** [comment] 2019-11-11 06:13
i hope sir you replay to me soon i need to finish my work and use your package if possible. appreciated 
zeinab
    On Monday, November 11, 2019, 12:59:49 PM GMT+8, Zeinab Mohamed <zeinabmohamed86@yahoo.com> wrote:  
 
  
dear sir,
i have run the manual code as you told me there is also error massage in this command
active_snws <- active_snw_search(processed_data, pin_path, snws_file = "subnetworks", search_method = "GR")
#Error in pathfindR::filterActiveSnws(active_snw_path = snws_file, sig_genes_vec = input_for_search$GENE, :
The active subnetwork file does not exist! Check the active_snw_path argument
    On Monday, November 11, 2019, 9:49:43 AM GMT+8, Ege Ulgen <notifications@github.com> wrote:  
 
 
RA_input was tested with run_pathfindR on multiple platforms so this is very odd. Can you try a manual run? see here

**Comment by egeulgen** [comment] 2019-11-11 09:13
Is there a directory called "active_snw_search" containing "input_for_search.txt' as well "subnetworks.txt"?

It's possible that you do not have write permissions in the working directory you're running the analysis. try running `file.access(".",  2)` and the output is 0 for success and -1 for failure.

**Comment by ajawd** [comment] 2019-11-12 03:18
i have inside my directory file generated called "active_snw_search" containing "input_for_search.txt' but no such file called "subnetworks.txt"
file.access(".", 2) i have run this code and the result was 0 which is sucess
today i have tried to run this code again 
it work so how i suppose to see the results ? because after i run both codes 
library(pathfindR)
processed_data <- input_processing(input = RA_input, 
                                 p_val_threshold = 0.05,
                                 pin_name_path = "Biogrid",
                                 convert2alias = TRUE)
pin_path <- return_pin_path(pin_name_path = "Biogrid")
active_snws <- active_snw_search(processed_data, pin_path, snws_file = "subnetworks", search_method = "GR")
enrichment_res <- enrichment_analyses(snws = active_snws, 
                                      sig_genes_vec = input_processed$GENE,
                                      pin_name_path = "Biogrid",
                                      genes_by_term = kegg_genes,
                                      term_descriptions = kegg_descriptions)
what should i do next?
i would like to present the results as you showed in biostars

**Comment by ajawd** [comment] 2019-11-12 03:32
i have tried also to run the code 
RA_output <- run_pathfindR(my data)
the results always the same 

`n_processes` is set to `iterations` because `iterations` < `n_processes` There is already a directory named "pathfindR_Results". Writing the result to "pathfindR_Results(5)" not to overwrite any previous results. ## Testing input The input looks OK ## Processing input. Converting gene symbols,           if necessary (and if human gene symbols provided) Number of genes provided in input: 572 Number of genes in input after p-value filtering: 572 Could not find any interactions for 11 (1.92%) genes in the PIN Final number of genes in input: 561 ## Performing Active Subnetwork Search and Enrichment ## Processing the enrichment results over all iterations ## Annotating involved genes and visualizing enriched terms Downloading pathway diagrams of 93 KEGG pathways    \|                                                                                                                                           \|   0%Cannot reach URL, please check your connection: hsa03040 Here's the original error message: 'wget' call had nonzero exit statusError in tryCatch({ : object 'status' not found

**Comment by egeulgen** [comment] 2019-11-12 15:52
ok, the latest error you get is related to a connection issue: ` 'wget' call had nonzero exit statusError`. You could (a) figure out what is the issue with wget or (b) run pathfindR without visualizing colored pathway diagrams, i.e. `output_df <- run_pathfindR(input_df, visualize_enriched_terms = FALSE)`.

I will make some changes so that when downloading a KEGG file fails, the visualization for that pathway is skipped and close this issue as the error you get is no longer related to pathfindR but wget.

**Closed** 2019-11-12 16:35 UTC

**Comment by ajawd** [comment] 2019-11-12 23:39
Dear Sir, I have send you messages at github but it seems that you are busy so didn't replay. The issues appear in the package can't be solved by me or any one expertise beside you that is why realing of the package compromise with a lot of questions and issues.  I really like your package I would like to use it all with visualization.  Could you politely read my messages  at github the last two messages? 
appreciated your time and efforts 
Zeinab
PhD student , department of bioinformatics and genomics China pharmaceutical university 

Sent from Yahoo Mail on Android 
 
  On Mon, Nov 11, 2019 at 5:13 PM, Ege Ulgen<notifications@github.com> wrote:   
Is there a directory called "active_snw_search" containing "input_for_search.txt' as well "subnetworks.txt"?

It's possible that you do not have write permissions in the working directory you're running the analysis. try running file.access(".", 2) and the output is 0 for success and -1 for failure.

**Comment by egeulgen** [comment] 2019-11-12 23:52
Dear @ajawd,
I did read all your messages and explained that the error seems to be related to [wget](http://gnuwin32.sourceforge.net/packages/wget.htm) as you get the error `'wget' call had nonzero exit status`. 

I also made changes the package so that when downloading a KEGG file fails, the visualization for that pathway is skipped. To be able to run pathfindR with this changes, please install the development version via:

```r
install.packages("devtools") # if you have not installed "devtools"
devtools::install_github("egeulgen/pathfindR")
```

Do let me know if you have any further questions,
Best,
-E
